trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- script: chmod +x ./gradlew
  displayName: Make gradlew executable

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'  # Path to your Gradle wrapper
    tasks: 'build'                # Replace with the tasks you want to run
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
  env:
    GRADLE_OPTS: '-Xmx3072m'      # JVM options here
